### ISSUE TITLE
请教一下如何验证收发包程序

### ISSUE THREAD

**Issue by haidfs** [shangweixie/udp_dpdk#1]
想请教一下如何验证收包与发包程序，我理解收包是在源server运行udp_sender，在目的端用nc/tshark/tcpdump这一类的工具进行查看，但是我的环境好像抓不到对应的包。最初我自己用Linux内核构造的报文，也抓不到。想请问下你的发包程序，能否在目的ip用抓包工具验证，程序的两个ip地址，是直连的ip地址或同一server的两个网口吗？还是通过交换机连接的？

**Comment by shangweixie** [comment]
源码里面的一些参数需要改，而且网卡需要打开混杂模式。

**Comment by haidfs** [comment]
> 源码里面的一些参数需要改，而且网卡需要打开混杂模式。

我的环境是这样的，两台机器A,B都有eth0、eth1、eth2三个网口，都是eth0作为管理口网卡，A,B的eth0 ip地址分别为X.X.X.160,X.X.X.161，两台机器上的eth1、eth2都绑定了DPDK。修改了代码中的src_ip为X.X.X.160，dst_ip为X.X.X.161，目的mac地址为全f。在160上起了udp_sent，在161用nc -ul 6666进行监听，但是监听不到udp的包，这样的配置是否有问题？eth0网卡混杂模式已打开，eth1，eth2的dpdk网卡混杂模式在你的代码里面也打开了，也监听不到。所以想请教下大神看这里面是不是配置有问题？两台服务器不是用网线直接连接的，走交换机。

**Comment by shangweixie** [comment]
抱歉，刚看到。我觉得可能是udp_sent构造的包没有计算正确的IP校验码，所以在接受端被IP层过滤掉了。你可以考虑使用tcpdump工具接收原始的以太网帧试一试。我这时间有点久了，忘记了我当时的实验环境了。

**Comment by haidfs** [comment]
好的，多谢
